server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:///Users/namelos/dev/java/spring-microservices/confsvr/src/main/resources/config/licensingservice
