server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/namelos/spring-microservices-config
          searchPaths: licensingservice
